<!DOCTYPE html>
<html>
<#import "macro/ui.ftlh" as ui/>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Brand</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cabin:700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/styles.min.home.css">
</head>
<body id="page-top">
<@ui.navbar/>
<header class="masthead" style="background-image: url('assets/img/beats.jpg');">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto"><h1 class="brand-heading">HEY, nickname!</h1>
                    <p class="intro-text">34 beats is available now for purchasing!<br>You have 3 booked beats now!</p>
                </div>
            </div>
        </div>
    </div>
</header>
<section class="text-center content-section" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto"><h2>About grayscale</h2>
                <p>Grayscale is a free Bootstrap theme. It can be yours right now, simply download the template on&nbsp;<a
                            href="#">the preview page</a>. The theme is open source, and you can use it for any purpose,
                    personal or commercial.</p>
                <p>This theme features stock photos by&nbsp;<a href="#">Gratisography</a>&nbsp;along with a custom
                    Google Maps skin courtesy of&nbsp;<a href="#">Snazzy Maps</a>.</p>
                <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with SASS and LESS files for
                    easy customization!</p></div>
        </div>
    </div>
</section>
<@ui.footer/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="assets/js/script.min.home.js"></script>
</body>
</html>