<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Brand</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cabin:700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/styles.min.index.css">
</head>
<body id="page-top">
<nav class="navbar navbar-light navbar-expand-md fixed-top" id="mainNav">
    <div class="container"><a class="navbar-brand js-scroll-trigger" href="#">antee</a>
        <button data-toggle="collapse" class="navbar-toggler navbar-toggler-right" data-target="#navbarResponsive"
                type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"
                value="Menu"><i class="fa fa-bars"></i></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item nav-link js-scroll-trigger"><a class="nav-link active js-scroll-trigger"
                                                                   href="#about">About</a></li>
                <li class="nav-item nav-link js-scroll-trigger"><a class="nav-link js-scroll-trigger" href="#download">beats</a>
                </li>
                <li class="nav-item nav-link js-scroll-trigger"><a class="nav-link js-scroll-trigger" href="#contact">contact</a>
                </li>
                <li class="nav-item nav-link js-scroll-trigger"></li>
                <li class="nav-item nav-link js-scroll-trigger">
                    <button class="btn btn-primary" type="button">SIGN IN/UP</button>
                </li>
            </ul>
        </div>
    </div>
</nav>
<header class="masthead" style="background-image: url('assets/img/ableton.jpg');">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto"><h1 class="brand-heading">antee prod.</h1>
                    <p class="intro-text">Different beat variations for you .<br>Created with soul.<br>Created with
                        love.</p><a class="btn btn-link btn-circle" role="button" href="#about"><i
                                class="fa fa-angle-double-down animated"></i></a></div>
            </div>
        </div>
    </div>
</header>
<section class="text-center content-section" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto"><h2>About me</h2>
                <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with SASS and LESS files for
                    easy customization!</p></div>
        </div>
    </div>
</section>
<section class="text-center download-section content-section" id="download"
         style="background-image: url('assets/img/beats.jpg');">
    <div class="container">
        <div class="col-lg-8 mx-auto"><h1>some of beats</h1>
            <h1>some of beats</h1>
            <h1>some of beats</h1>
            <h1>some of beats</h1></div>
    </div>
    <div class="container">
        <div class="intro"></div>
    </div>
</section>
<section class="text-center content-section" id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto"><h2>Contact me</h2>
                <ul class="list-inline banner-social-buttons">
                    <li class="list-inline-item">&nbsp;<button class="btn btn-primary btn-lg btn-default" type="button">
                            <i class="fa fa-soundcloud fa-fw"></i><span class="network-name">&nbsp; scloud</span>
                        </button>
                    </li>
                    <li class="list-inline-item">&nbsp;<button class="btn btn-primary btn-lg btn-default" type="button">
                            <i class="fa fa-instagram fa-fw"></i><span class="network-name">&nbsp;insta</span></button>
                    </li>
                    <li class="list-inline-item">&nbsp;<button class="btn btn-primary btn-lg btn-default" type="button">
                            <i class="fa fa-envelope-o fa-fw"></i><span class="network-name">&nbsp;email</span></button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<div class="map-clean"></div>
<footer>
    <div class="container text-center"><p>Copyright © Antee 2021</p></div>
</footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="assets/js/script.min.index.js"></script>
</body>
</html>